---
up: "[[2024-W19]]"
description: ""
publish: false
starred: false
status: ""
type: note
tags:
  - periodic/daily
cssclasses:
  - "cards"
  - "cards-cols-1"
obsidianUIMode: source
obsidianEditingMode: live
template: "[[Daily]]"
created: 20240506000100
modified: 20240507000540
aliases:
  - Monday - May 6th 2024
linter-yaml-title-alias: Monday - May 6th 2024
title: Monday - May 6th 2024
id: 10
week: "[[2024-W19]]"
yearly: "[[2024]]"
quarterly: "[[2024-Q2]]"
monthly: "[[2024-05]]"
daily: "[[2024-05-06]]"
month: "May"
weekday: Monday
---

# Monday - May 6th 2024

Add notes

Cmd center and express admin.

Based on configuration.

- Debug should be in dev, but production should

But if production, debug enabled.

---

`step.py` called by the API

---

Ask [[kamil]] if task metrics has anyway to tie the tasks to clusters themselves.

---

SRE router Atlas config

`entrypoint.sh`

---

Running into issue on the staging step (unrelated to staging itself), that is indicating that we might need to investigate some cert issues.

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='sretestsmf1.medallia.com', port=443): Max retries exceeded with url: /oauth/sretestsmf1/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
```

When prov-ng tries to connect to: https://sretestsmf1.medallia.com/oauth/sretestsmf1/token, we get SSL error. As a result, we cannot get an access token when trying to list the available packages.

---

Here's how you could format your update for JIRA:

---

```
scp erauner@ssh1:/sharedfs/ops/bin/clis-1.5.0-all.jar .
scp erauner@ssh1:/sharedfs/ops/bin/clis-2.8.1-all.jar .
scp erauner@ssh1:/sharedfs/ops/bin/qastaging .
scp erauner@ssh1:/sharedfs/ops/bin/titan .
scp erauner@ssh1:/sharedfs/ops/bin/sbx .
```

```
scp clis-1.5.0-all.jar erauner@ssh1-smf1:/home/erauner
scp clis-2.8.1-all.jar erauner@ssh1-smf1:/home/erauner
scp qastaging erauner@ssh1-smf1:/home/erauner
scp titan erauner@ssh1-smf1:/home/erauner
scp sbx erauner@ssh1-smf1:/home/erauner
scp medallia-java-cli erauner@ssh1-smf1:/home/erauner
scp clis-all.jar erauner@ssh1-smf1:/home/erauner
```

```
scp clis-1.5.0-all.jar erauner@ssh1-smf1:/home/erauner
scp clis-2.8.1-all.jar erauner@ssh1-smf1:/home/erauner
scp qastaging erauner@ssh1-smf1:/home/erauner
scp titan erauner@ssh1-smf1:/home/erauner
scp sbx erauner@ssh1-smf1:/home/erauner
```

```
sudo mv ./clis-1.5.0-all.jar /sharedfs/ops/bin/
sudo mv ./clis-2.8.1-all.jar /sharedfs/ops/bin/
sudo mv ./qastaging /sharedfs/ops/bin/
sudo mv ./titan /sharedfs/ops/bin/
sudo mv ./sbx /sharedfs/ops/bin/
```

```
2024-05-06 17:47:48,367 DEBUG connectionpool Starting new HTTPS connection (1): sre-provisioning-api-dev.den.medallia.com:443
2024-05-06 17:47:48,597 DEBUG connectionpool https://sre-provisioning-api-dev.den.medallia.com:443 "PUT /api/v1/internal/status/ HTTP/1.1" 400 46
2024-05-06 17:47:48,601 ERROR step step 'StepStaging' failed in '_perform' with: step failed with step 'StepStaging' failed in 'perform' with: failed to create/complete staging for sretestsmf1 with: failed to run staging for sretestsmf1 with: OperationFailedException(message="com.medallia.atlas.qastaging.plans.shared.StagingPlanFragmentManager$PlanFragmentGenerationFailedException: Failed to generate REDUCE plan: java.util.concurrent.ExecutionException: BadRequestException(message:ClusterId(clusterName:express.sretestsmf1, environment:smf1.medallia.com) doesn't exist)")
Traceback (most recent call last):
  File "/Users/erauner/.pyenv/versions/3.9.7/envs/provisioning-ng/lib/python3.9/site-packages/medallia_sre/staging.py", line 95, in run_staging
    return self._client.triggerStaging(param)
  File "/Users/erauner/.pyenv/versions/3.9.7/envs/provisioning-ng/lib/python3.9/site-packages/thriftpy2/thrift.py", line 219, in _req
    return self._recv(_api)
  File "/Users/erauner/.pyenv/versions/3.9.7/envs/provisioning-ng/lib/python3.9/site-packages/thriftpy2/thrift.py", line 251, in _recv
    raise v
qastaging_thrift.OperationFailedException: OperationFailedException(message="com.medallia.atlas.qastaging.plans.shared.StagingPlanFragmentManager$PlanFragmentGenerationFailedException: Failed to generate REDUCE plan: java.util.concurrent.ExecutionException: BadRequestException(message:ClusterId(clusterName:express.sretestsmf1, environment:smf1.medallia.com) doesn't exist)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/erauner/git/provisioning-ng/prov_platform/mec/MecProvisionInstance/step_staging.py", line 72, in perform
    self._client.run_staging(self.instance_name())
  File "/Users/erauner/.pyenv/versions/3.9.7/envs/provisioning-ng/lib/python3.9/site-packages/medallia_sre/staging.py", line 97, in run_staging
    raise StagingException(f"failed to run staging for {cluster_name} with: {e}") from e
medallia_sre.staging.StagingException: failed to run staging for sretestsmf1 with: OperationFailedException(message="com.medallia.atlas.qastaging.plans.shared.StagingPlanFragmentManager$PlanFragmentGenerationFailedException: Failed to generate REDUCE plan: java.util.concurrent.ExecutionException: BadRequestException(message:ClusterId(clusterName:express.sretestsmf1, environment:smf1.medallia.com) doesn't exist)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/erauner/git/provisioning-ng/lib/abstract_step.py", line 710, in _perform
    self.perform()
  File "/Users/erauner/git/provisioning-ng/prov_platform/mec/MecProvisionInstance/step_staging.py", line 75, in perform
    raise StepStagingException(
prov_platform.mec.MecProvisionInstance.step_staging.StepStagingException: step 'StepStaging' failed in 'perform' with: failed to create/complete staging for sretestsmf1 with: failed to run staging for sretestsmf1 with: OperationFailedException(message="com.medallia.atlas.qastaging.plans.shared.StagingPlanFragmentManager$PlanFragmentGenerationFailedException: Failed to generate REDUCE plan: java.util.concurrent.ExecutionException: BadRequestException(message:ClusterId(clusterName:express.sretestsmf1, environment:smf1.medallia.com) doesn't exist)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/erauner/git/provisioning-ng/step.py", line 156, in <module>
    step._perform()
  File "/Users/erauner/git/provisioning-ng/lib/abstract_step.py", line 718, in _perform
    raise AbstractStepException(f"step failed with {ex}") from ex
lib.abstract_step.AbstractStepException: step 'StepStaging' failed in '_perform' with: step failed with step 'StepStaging' failed in 'perform' with: failed to create/complete staging for sretestsmf1 with: failed to run staging for sretestsmf1 with: OperationFailedException(message="com.medallia.atlas.qastaging.plans.shared.StagingPlanFragmentManager$PlanFragmentGenerationFailedException: Failed to generate REDUCE plan: java.util.concurrent.ExecutionException: BadRequestException(message:ClusterId(clusterName:express.sretestsmf1, environment:smf1.medallia.com) doesn't exist)")
2024-05-06 17:47:48,607 CRITICAL step step failed with exception: step 'StepStaging' failed in '_perform' with: step failed with step 'StepStaging' failed in 'perform' with: failed to create/complete staging for sretestsmf1 with: failed to run staging for sretestsmf1 with: OperationFailedException(message="com.medallia.atlas.qastaging.plans.shared.StagingPlanFragmentManager$PlanFragmentGenerationFailedException: Failed to generate REDUCE plan: java.util.concurrent.ExecutionException: BadRequestException(message:ClusterId(clusterName:express.sretestsmf1, environment:smf1.medallia.com) doesn't exist)"), cause: step 'StepStaging' failed in 'perform' with: failed to create/complete staging for sretestsmf1 with: failed to run staging for sretestsmf1 with: OperationFailedException(message="com.medallia.atlas.qastaging.plans.shared.StagingPlanFragmentManager$PlanFragmentGenerationFailedException: Failed to generate REDUCE plan: java.util.concurrent.ExecutionException: BadRequestException(message:ClusterId(clusterName:express.sretestsmf1, environment:smf1.medallia.com) doesn't exist)"), context: step 'StepStaging' failed in 'perform' with: failed to create/complete staging for sretestsmf1 with: failed to run staging for sretestsmf1 with: OperationFailedException(message="com.medallia.atlas.qastaging.plans.shared.StagingPlanFragmentManager$PlanFragmentGenerationFailedException: Failed to generate REDUCE plan: java.util.concurrent.ExecutionException: BadRequestException(message:ClusterId(clusterName:express.sretestsmf1, environment:smf1.medallia.com) doesn't exist)"), exiting.
```


---
