---
up: "[[2024-W16]]"
description: ""
publish: false
starred: false
status: ""
type: note
tags:
  - periodic/daily
cssclasses:
  - "cards"
  - "cards-cols-1"
obsidianUIMode: source
obsidianEditingMode: live
template: "[[Daily]]"
created: 20240415000100
modified: 20240416100824
aliases:
  - Monday - April 15th 2024
linter-yaml-title-alias: Monday - April 15th 2024
title: Monday - April 15th 2024
id: 10
week: "[[2024-W16]]"
yearly: "[[2024]]"
quarterly: "[[2024-Q2]]"
monthly: "[[2024-04]]"
daily: "[[2024-04-15]]"
month: "April"
weekday: Monday
---

# Monday - April 15th 2024

Reach out to MDBS  
Being asked about it in a new slack channel here now:

[https://medallia.slack.com/archives/C044QEX5Z0F/p1713206999437629?thread_ts=1713196289.621889&cid=C044QEX5Z0F](https://medallia.slack.com/archives/C044QEX5Z0F/p1713206999437629?thread_ts=1713196289.621889&cid=C044QEX5Z0F)

[**`sacramento-datacenter`**](https://medallia.slack.com/archives/C044QEX5Z0F/p1713196289621889)

---

Reach out to MDBS

```
self.task_name = f"k8s/{self.dc()}/{self.vars.topology.namespace}/{self.full_db_name}"
```

I'm seeing something wrong on our end here: `fab docker.psql:k8s/smf1/None/smf1-prod-db-sretestsmf1`

---

Investigate None error  
Investigate None error

---

Investigate None error

```
self.task_name = f"k8s/{self.dc()}/{self.vars.topology.namespace}/{self.full_db_name}"
```

[provisioning-ng/prov_platform/mec/MecProvisionInstance/step_db_pgscripts.py at master · medallia/provisioning-ng](https://github.medallia.com/medallia/provisioning-ng/blob/master/prov_platform/mec/MecProvisionInstance/step_db_pgscripts.py)

…

[SRE UI | Log db-pgscripts for task MecProvisionInstance - sretestsmf1 - Task automation-zperustnaktr30b](https://sre-provisioning-api-dev.den.medallia.com/ui/log/automation-zperustnaktr30b/db-pgscripts)

---

Investigate None error  
check the vars to see what `self.vars.topology.namespace` is

---

Investigate None error  
[SRE UI | Vars MecProvisionInstance for task sretestsmf1 - Task automation-zperustnaktr30b](https://sre-provisioning-api-dev.den.medallia.com/ui/vars/automation-zperustnaktr30b)

---

Investigate None error  
check the vars to see what `self.vars.topology.namespace` is

[SRE UI | Vars MecProvisionInstance for task sretestsmf1 - Task automation-zperustnaktr30b](https://sre-provisioning-api-dev.den.medallia.com/ui/vars/automation-zperustnaktr30b)

---

Investigate None error

```
name: sretestsmf1
  namespace: null
```

This is the problem:

[SRE UI | Vars MecProvisionInstance for task sretestsmf1 - Task automation-zperustnaktr30b](https://sre-provisioning-api-dev.den.medallia.com/ui/vars/automation-zperustnaktr30b)

---

Investigate None error  
Add the namespace yourself to the vars and re-approve.

Then:  
Log a jira to fix that issue for the DB step for new smf1 dc. Need to figure out why it's happening

---

Investigate None error

```
export CONTEXT=den;kubectl exec -i -t $(kubectl get pods --context $CONTEXT -n sre-provisioning | grep sre-provisioning-api-server | awk '{print $1}') --context $CONTEXT -n sre-provisioning -- /bin/bash
```

`vi /var/provision/api/workdir/wf/mec/sretestsmf1/MecProvisionInstance/SREPROV-216/vars.yaml`

---

Investigate None error  
What sets the vars in the namspace anyway?

Ahh I guess it was because we had to skip the namespace step:

[provisioning-ng/prov_platform/mec/MecProvisionInstance/step_k8s_namespace.py at master · medallia/provisioning-ng](https://github.medallia.com/medallia/provisioning-ng/blob/master/prov_platform/mec/MecProvisionInstance/step_k8s_namespace.py)

---

Investigate None error  
Ran it again:

[SRE UI | MecProvisionInstance - sretestsmf1 - Task automation-y5ppxa4n9dmjygi](https://sre-provisioning-api-dev.den.medallia.com/ui/task/automation-y5ppxa4n9dmjygi)

…

Will follow it up an relay to DB what happens

---

Investigate None error  
Ran it again:

[SRE UI | MecProvisionInstance - sretestsmf1 - Task automation-y5ppxa4n9dmjygi](https://sre-provisioning-api-dev.den.medallia.com/ui/task/automation-y5ppxa4n9dmjygi)

[automation-y5ppxa4n9dmjygi / sre-provisioning / Workflows - Argo](https://argo-workflow.den.medallia.com/workflows/sre-provisioning/automation-y5ppxa4n9dmjygi?tab=workflow)

…

Will follow it up an relay to DB what happens

---

Investigate None error  
Ran it again:

[SRE UI | MecProvisionInstance - sretestsmf1 - Task automation-y5ppxa4n9dmjygi](https://sre-provisioning-api-dev.den.medallia.com/ui/task/automation-y5ppxa4n9dmjygi)

[automation-y5ppxa4n9dmjygi / sre-provisioning / Workflows - Argo](https://argo-workflow.den.medallia.com/workflows/sre-provisioning/automation-y5ppxa4n9dmjygi?tab=workflow)

…

will follow it up an [relay to DB](https://medallia.slack.com/archives/C8W420RDX/p1713213814510249?thread_ts=1712856219.682339&cid=C8W420RDX) what happens

---

Reach out to Lean about the kafkfa step  
Reach out to Lean about the kafkfa step > troubleshoot provisioning steps > provision a test cluster in smf1 for varsamis

---

Investigate None error  
Failed again, but we at least got past that error

---

Investigate None error

```
Job k8s/smf1/tenant-124478-prod/smf1-prod-db-sretestsmf1-setup is in status Running on None since 2024-04-15T20:51:54Z
```

- for some reason, it is `None`. Perhaps due to this: `Fatal error: Needed to prompt for a connection or sudo password`

```
./pods sretestsmf1
NAME                                   READY   STATUS
smf1-prod-db-sretestsmf1-setup-xwjnc   0/1     Completed
```

- Setup appeared to have failed.

I think you need to restart the DB provision again after taking these steps:

[Handling DB Provision Failure - PROV-NG - Pacific](https://pacific.medallia.com/display/PROVNG/Handling+DB+Provision+Failure)

---

Investigate None error

```
kubectl drain smf1-r11-u10 --ignore-daemonsets --delete-emptydir-data --context smf1
kubectl cordon smf1-r11-u10 --context smf1
```

---

Investigate None error  
Running it again after running through the steps to restart

[SRE UI | MecProvisionInstance - sretestsmf1 - Task automation-uc6cmyelctzvjtr](https://sre-provisioning-api-dev.den.medallia.com/ui/task/automation-uc6cmyelctzvjtr)

…

Follow back up on this to see if it fails

---

Investigate None error  
Investigate None error > reach out to MDBS > troubleshoot provisioning steps > provision a test cluster in smf1 for varsamis

---

Reach out to MDBS  
Reach out to MDBS > troubleshoot provisioning steps > provision a test cluster in smf1 for varsamis

---

Troubleshoot provisioning steps  
Troubleshoot provisioning steps > provision a test cluster in smf1 for varsamis

---
